### ISSUE TITLE
Hashes don't match with hashes of standard sha256sum tool

### ISSUE THREAD

**Issue by m1cm1c** [matejcik/fastsum#1]
Sometimes, the hashes are the same. Sometimes, they are not:

```
$ touch file
$ sha256sum file
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  file
$ ./fastsum file
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  file
$ echo a > file
$ sha256sum file 
87428fc522803d31065e7bce3cf03fe475096631e5e07bbd7a0fde60c4cf25c7  file
$ ./fastsum file 
225f1bbbc4b1a3d97c622a492d91ea8d6858d7e1164bbbb5953f74311d6d222e  file
```

**Comment by matejcik** [comment]
(wow, someone tried to use this? wow!)

anyway
the sums are not supposed to be the same, they are only comparable with what `fastsum` produces.

the result is a two-level hash: take SHA256 of every 16kB block of the file, and then take a SHA256 of the hashes you got from the blocks.

you get the same results for an empty file, because there's no blocks, so input to the second SHA is empty, so it's the same as what sha256sum does

for files < 16 kB, you get the same if you do this:
```
$ echo a > file
$ sha256sum file
87428fc522803d31065e7bce3cf03fe475096631e5e07bbd7a0fde60c4cf25c7  a
$ sha256sum file | xxd -r -p - | sha256sum
225f1bbbc4b1a3d97c622a492d91ea8d6858d7e1164bbbb5953f74311d6d222e -
```
(the `xxd` converts the hex-formatted hash to bytes)
